name: Sitemap Auto Update

on:
  schedule:
    - cron: '0 0 * * *'  # দৈনিক রাত ১২টায়
  workflow_dispatch:  # ম্যানুয়াল রান করার অপশন

permissions:
  contents: write

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate Sitemap
      run: python .github/scripts/sitemap_generator.py

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global pull.rebase false
        
        # শুধু sitemap.xml এর পরিবর্তন চেক
        if git diff --exit-code --quiet sitemap.xml; then
          echo "No changes in sitemap.xml"
          exit 0
        fi

        git add sitemap.xml
        git commit -m "Auto-updated sitemap [skip ci]"
        
        # Conflict এড়াতে রিসেট করে নতুন করে কমিট
        git pull origin main || (
          git reset --hard origin/main
          git add sitemap.xml
          git commit -m "Auto-updated sitemap [skip ci]"
        )
        
        git push origin main
