name: Sitemap Auto Update

on:
  schedule:
    - cron: '0 0 * * *'  # দৈনিক রাত ১২টায়
  workflow_dispatch:     # ম্যানুয়াল রান অপশন

permissions:
  contents: write

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: main-repo  # স্পেসিফিক পাথ সেট করুন

    - name: Verify Script Existence
      run: |
        echo "Current directory: $(pwd)"
        echo "Checking script path..."
        ls -la main-repo/.github/scripts/
        if [ ! -f main-repo/.github/scripts/generate_sitemap.py ]; then
          echo "Error: Script file not found!"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install xmltodict

    - name: Run Sitemap Generator
      working-directory: main-repo  # সঠিক ওয়ার্কিং ডিরেক্টরি
      run: python .github/scripts/generate_sitemap.py

    - name: Commit and Push
      working-directory: main-repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add sitemap.xml
        git commit -m "Auto-updated sitemap [skip ci]" || echo "No changes"
        git pull origin main
        git push origin main
