name: Auto Update Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

permissions:
  contents: write

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Sitemap Generator
        run: python .github/scripts/generate_sitemap.py

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Using your provided PAT
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check for changes in sitemap.xml only
          if git diff --quiet sitemap.xml; then
            echo "No changes detected in sitemap.xml"
            exit 0
          fi
          
          # Stage only sitemap.xml
          git add sitemap.xml
          
          # Create commit
          git commit -m "Auto-update sitemap [skip ci]"
          
          # Pull latest changes with merge strategy
          git pull origin main
          
          # Push changes using the PAT
          git push "https://$GH_TOKEN@github.com/kamilhussen24/kamilhussen24.github.io.git" main
