name: Auto Update Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

permissions:
  contents: write

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Sitemap Generator
        run: python .github/scripts/generate_sitemap.py

      - name: Commit and Push Changes
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check for changes
          if git diff --quiet --exit-code; then
            echo "No changes detected"
            exit 0
          fi
          
          # Stage all changes (including sitemap.xml)
          git add -A
          
          # Create commit
          git commit -m "Auto-update sitemap [skip ci]"
          
          # Pull changes using merge strategy instead of rebase
          git pull origin main
          
          # Push changes
          git push origin main
