name: Auto Update Sitemap

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # প্রতিদিন রাত ১২টায়

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install xmltodict

      - name: Generate Sitemap
        run: |
          echo "বর্তমান ডিরেক্টরি: $(pwd)"
          python .github/scripts/generate_sitemap.py --force
          ls -la sitemap.xml  # ফাইল এক্সিস্টেন্স চেক করুন

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "🚀 সাইটম্যাপ আপডেট হয়েছে [skip ci]"
          git pull origin main
          git push origin main
