name: Auto Update Sitemap

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # প্রতিদিন রাত ১২টায়

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # কমিট করার পারমিশন

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # সম্পূর্ণ Git হিস্ট্রি পেতে

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install xmltodict

      - name: Generate Sitemap
        working-directory: .github/scripts  # সঠিক ডিরেক্টরিতে যান
        run: python generate_sitemap.py

      - name: Commit and Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # শুধু sitemap.xml চেক করুন
          if git diff --quiet sitemap.xml; then
            echo "No changes to commit"
            exit 0
          fi

          git add sitemap.xml
          git commit -m "🔄 Auto-updated sitemap [skip ci]"
          git pull origin main --rebase  # কনফ্লিক্ট এড়াতে
          git push origin main
